export const CURRENT_USER_AVAILABLE = 'CURRENT_USER_AVAILABLE'
export const CURRENT_USER_NOT_AVAILABLE = 'CURRENT_USER_NOT_AVAILABLE' 
export const WEB3_AVAILABLE = 'WEB3_AVAILABLE'
export const USER_EXISTS = 'USER_EXISTS'