export const USER_GEMS_RETRIEVED = 'USER_GEMS_RETRIEVED';
export const ALL_USER_GEMS_RETRIEVED = 'ALL_USER_GEMS_RETRIEVED';
export const ALL_USER_GEMS_UPLOADED = 'ALL_USER_GEMS_UPLOADED';
export const USER_HAS_NO_GEMS_IN_WORKSHOP = 'USER_HAS_NO_GEMS_IN_WORKSHOP';
export const AUCTION_DETAILS_RECEIVED = 'AUCTION_DETAILS_RECEIVED';
export const ONLY_WANT_TO_SEE_GEMS_IN_AUCTIONS = 'ONLY_WANT_TO_SEE_GEMS_IN_AUCTIONS';
export const WANT_TO_SEE_ALL_GEMS = 'WANT_TO_SEE_ALL_GEMS';
export const FETCH_USER_GEMS_BEGUN = 'FETCH_USER_GEMS_BEGUN';
export const FETCH_USER_GEMS_SUCCEEDED = 'FETCH_USER_GEMS_SUCCEEDED';
export const FETCH_USER_GEMS_FAILED = 'FETCH_USER_GEMS_FAILED';
export const FETCH_GEMS_PAGE_IMAGES = 'FETCH_GEMS_PAGE_IMAGES';

export const FETCH_USER_DETAILS_BEGUN = 'FETCH_USER_DETAILS_BEGUN';
export const FETCH_USER_DETAILS_SUCCEEDED = 'FETCH_USER_DETAILS_SUCCEEDED';
export const USER_DETAILS_RETRIEVED = 'USER_DETAILS_RETRIEVED';
export const FETCH_USER_DETAILS_FAILED = 'FETCH_USER_DETAILS_FAILED';

export const DASHBOARD_WAS_FILTERED = 'DASHBOARD_WAS_FILTERED';

export const RERENDER_SORT_BOX = 'RERENDER_SORT_BOX';
export const SORT_BOX_RERENDERED = 'SORT_BOX_RERENDERED';

export const PAGINATE = 'PAGINATE';
