export const USER_GEMS_RETRIEVED = 'USER_GEMS_RETRIEVED'
export const ALL_USER_GEMS_RETRIEVED = 'ALL_USER_GEMS_RETRIEVED'
export const ALL_USER_GEMS_UPLOADED = 'ALL_USER_GEMS_UPLOADED'
export const USER_HAS_NO_GEMS_IN_WORKSHOP = 'USER_HAS_NO_GEMS_IN_WORKSHOP'
export const AUCTION_DETAILS_RECEIVED = "AUCTION_DETAILS_RECEIVED"
export const NEW_AUCTION_CREATED = "NEW_AUCTION_CREATED"
