export const COUNTRY_LIST = [
    "Russia",
    "Canada",
    "China",
    "United States of America",
    "Brazil",
    "Australia",
    "India",
    "Argentina",
    "Kazakhstan",
    "Algeria",
    "Democratic Republic of the Congo",
    "Greenland",
    "Saudi Arabia",
    "Mexico",
    "Indonesia",
    "Sudan",
    "Libya",
    "Iran",
    "Mongolia",
    "Peru",
    "Chad",
    "Niger",
    "Angola",
    "Mali",
    "South Africa",
    "Colombia",
    "Ethiopia",
    "Bolivia",
    "Mauritania",
    "Egypt",
    "Tanzania",
    "Nigeria",
    "Venezuela",
    "Namibia",
    "Pakistan",
    "Mozambique",
    "Turkey",
    "Chile",
    "Zambia",
    "Myanmar (Burma)",
    "France",
    "Afghanistan",
    "Somalia",
    "Central African Republic",
    "South Sudan",
    "Ukraine",
    "Botswana",
    "Madagascar",
    "Kenya",
    "Yemen",
    "Thailand",
    "Spain",
    "Turkmenistan",
    "Cameroon",
    "Papua New Guinea",
    "Sweden",
    "Uzbekistan",
    "Morocco",
    "Iraq",
    "Paraguay",
    "Zimbabwe",
    "Japan",
    "Germany",
    "Republic of the Congo",
    "Finland",
    "Malaysia",
    "Vietnam",
    "Norway",
    "Ivory Coast",
    "Poland",
    "Oman",
    "Italy",
    "Philippines",
    "Ecuador",
    "Burkina Faso",
    "New Zealand",
    "Gabon",
    "Guinea",
    "United Kingdom",
    "Uganda",
    "Ghana",
    "Romania",
    "Laos",
    "Guyana",
    "Belarus",
    "Kyrgyzstan",
    "Senegal",
    "Syria",
    "Cambodia",
    "Uruguay",
    "Tunisia",
    "Suriname",
    "Bangladesh",
    "Nepal",
    "Tajikistan",
    "Greece",
    "Nicaragua",
    "Eritrea",
    "North Korea",
    "Malawi",
    "Benin",
    "Honduras",
    "Liberia",
    "Bulgaria",
    "Cuba",
    "Guatemala",
    "Iceland",
    "South Korea",
    "Hungary",
    "Jordan",
    "Portugal",
    "Serbia",
    "Azerbaijan",
    "Austria",
    "United Arab Emirates",
    "Czech Republic",
    "Panama",
    "Sierra Leone",
    "Ireland",
    "Georgia",
    "Sri Lanka",
    "Lithuania",
    "Latvia",
    "Togo",
    "Croatia",
    "Bosnia and Herzegovina",
    "Costa Rica",
    "Slovakia",
    "Dominican Republic",
    "Bhutan",
    "Estonia",
    "Denmark",
    "Netherlands",
    "Switzerland",
    "Guinea-Bissau",
    "Republic of China (Taiwan, Quemoy, Matsu)",
    "Moldova",
    "Belgium",
    "Lesotho",
    "Armenia",
    "Albania",
    "Solomon Islands",
    "Equatorial Guinea",
    "Burundi",
    "Haiti",
    "Israel (Including West Bank and Gaza)",
    "Rwanda",
    "Macedonia",
    "Belize",
    "Djibouti",
    "El Salvador",
    "Slovenia",
    "Fiji",
    "Kuwait",
    "Swaziland",
    "East Timor",
    "Bahamas",
    "Montenegro",
    "Vanuatu",
    "Qatar",
    "Gambia",
    "Jamaica",
    "Lebanon",
    "Cyprus",
    "Brunei",
    "Trinidad and Tobago",
    "Cape Verde",
    "Samoa",
    "Luxembourg",
    "Comoros",
    "Mauritius",
    "São Tomé and Príncipe",
    "Dominica",
    "Tonga",
    "Kiribati",
    "Micronesia",
    "Singapore",
    "Bahrain",
    "Saint Lucia",
    "Seychelles",
    "Andorra",
    "Palau",
    "Antigua and Barbuda",
    "Barbados",
    "Saint Vincent and the Grenadines",
    "Grenada",
    "Malta",
    "Maldives",
    "Saint Kitts and Nevis",
    "Liechtenstein"
];