export const NEW_AUCTIONS_RECEIVED = "NEW_AUCTIONS_RECEIVED"
export const AUCTION_PRICE_UPDATES_BEGIN = "AUCTION_PRICE_UPDATES_BEGIN"
export const MARKETPLACE_WAS_FILTERED = "MARKETPLACE_WAS_FILTERED"
export const FETCH_NEW_AUCTIONS_FAILED = "FETCH_NEW_AUCTIONS_FAILED"
export const FETCH_NEW_AUCTIONS_BEGUN = "FETCH_NEW_AUCTIONS_BEGUN"

  
export const FETCH_NEW_AUCTIONS_SUCCEEDED = "FETCH_NEW_AUCTIONS_SUCCEEDED"

export const MARKETPLACE_FILTER_BEGUN = "MARKETPLACE_FILTER_BEGUN"
export const MARKETPLACE_FILTER_FAILED = "MARKETPLACE_FILTER_FAILED"

  

