export const NEW_AUCTIONS_RECEIVED = "NEW_AUCTIONS_RECEIVED"
export const AUCTION_PRICE_UPDATES_BEGIN = "AUCTION_PRICE_UPDATES_BEGIN"
export const MARKETPLACE_WAS_FILTERED = "MARKETPLACE_WAS_FILTERED"


