export const WEB3_ADDED = 'WEB3_ADDED'
export const DUTCH_CONTRACT_ADDED = 'DUTCH_CONTRACT_ADDED'
export const GEM_CONTRACT_ADDED = 'GEM_CONTRACT_ADDED'

export const FETCH_DATA_BEGUN   = 'FETCH_DATA_BEGUN';
export const FETCH_DATA_SUCCEEDED = 'FETCH_DATA_SUCCEEDED';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';
