export const SALE_STATE_RECEIVED = 'SALE_STATE_RECEIVED';
export const USER_BALANCE_RECEIVED = 'USER_BALANCE_RECEIVED';
export const CHEST_VALUE_RECEIVED = 'CHEST_VALUE_RECEIVED';
export const FOUNDERS_KEYS_ISSUED = 'FOUNDERS_KEYS_ISSUED';
export const SUBMITTED_KEYS_RECEIVED = 'SUBMITTED_KEYS_RECEIVED';
export const SUBMITTED_KEYS_BY_USER_RECEIVED = 'SUBMITTED_KEYS_BY_USER_RECEIVED';