export const RESOLVE_PENDING_TRANSACTIONS = 'RESOLVE_PENDING_TRANSACTIONS';
export const TX_STARTED = 'TX_STARTED';
export const TX_CONFIRMATIONS = 'TX_CONFIRMATIONS';
export const TX_COMPLETED = 'TX_COMPLETED';
export const TX_ERROR = 'TX_ERROR';
