export const AUCTION_DETAILS_RECEIVED = "AUCTION_DETAILS_RECEIVED"
export const NEW_AUCTION_CREATED ='NEW_AUCTION_CREATED'
export const OWNERSHIP_TRANSFERRED = "OWNERSHIP_TRANSFERRED"
export const CLEAR_GEM_PAGE = "CLEAR_GEM_PAGE"
